### ISSUE TITLE
The noise level 

### ISSUE THREAD

**Issue by yunshihuang** [csdwren/SelfDeblur#16]
Hello,

Firstly, thanks for the great contribution and the open access to the code!

My question is that I want to apply this algorithm on my own datasets, say that I have a blurry noisy image, with known noise level and blur kernel size. I notice that in your code like selfdeblur_levin.py line 48 there is one setting called 'reg_noise_std = 0.001', does this refer to the regularization parameter \lambda in Eq.6 in your paper? If so, why you did not set it as 10^-6 as you said in Section 4.1 (10\times std of noise level), if not, what is this setting? 

Another question is that if I understand correctly, your algorithm is an unsupervised one so that we do not need to train a generalized model using training sets, instead we directly apply the algorithm on the blurry noisy images one by one, right? Does your algorithm have some limitations to the noise level? If the noise std is relatively big, say 0.1, would it still work well?

Any reply is appreciated!

**Comment by csdwren** [comment]
1. Because blurry images in levin datasets are with very low noise levels. After the acceptance, I found that it achieved better results by setting lambda=0. The setting lambda=10 x std is an empecial recommendation, and I cannot guarantee it is optimal choice. 
2. Yes. SelfDeblur needs to process image one-by-one. 
3. SelfDeblur may fail to handle high level noisy images, since high level noises may break the convolution blur degradation, which is the basic assumption. For blurry image with std 0.1, SelfDeblur may fail.

**Comment by yunshihuang** [comment]
Thanks so much for the reply!
